### ISSUE TITLE
Implement Reviews section

### ISSUE THREAD

**Issue by rayvafa** [rayvafa/heathcote-fish-n-chips#21]
Create a page like following image. all the code goes to `Review.js` and `Review.css`

![screen shot 2017-07-08 at 3 04 02 pm](https://user-images.githubusercontent.com/3222063/27982753-bade80f0-63ee-11e7-8bc7-8edf9c454332.png)

**Comment by johibkhan2** [comment]
it is completed and code is committed in branch end with johib

**Comment by rayvafa** [comment]
I close the ticket when the code is approved and merged.

**Comment by rayvafa** [comment]
https://github.com/rayvafa/heathcote-fish-n-chips/pull/24
